-- SQL commands to create the database schema.
--
-- If you have not created the tables yet, run the CREATE TABLE statements.
-- If you have already created the semantic_analysis table, run the ALTER TABLE statement.


-- CREATE TABLE statements
CREATE TABLE public.call_history (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  caller_number text,
  recipient_number text,
  call_duration integer, -- in seconds
  recording_url text,
  transcript text,
  tour_date timestamp with time zone,
  name text
);

CREATE TABLE public.semantic_analysis (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  call_id bigint references public.call_history(id) on delete cascade,
  sentiment text,
  sentiment_score float,
  agent_confidence float,
  positive_indicators jsonb,
  negative_indicators jsonb,
  predicted_outcome text,
  alert_status text,
  finish_reason text,
  stop text,
  avg_logprobs float,
  conversation_duration_seconds integer,
  total_customer_words integer,
  agent_talk_time_percentage float,
  buying_signals jsonb,
  summary text

);


/*
-- ALTER TABLE statement
-- Use this if you have already created the semantic_analysis table
-- and want to add the new columns.

ALTER TABLE public.semantic_analysis
ADD COLUMN sentiment_score float,
ADD COLUMN agent_confidence float,
ADD COLUMN positive_indicators jsonb,
ADD COLUMN negative_indicators jsonb,
ADD COLUMN predicted_outcome text,
ADD COLUMN alert_status text,
ADD COLUMN finish_reason text,
ADD COLUMN stop text,
ADD COLUMN avg_logprobs float,
ADD COLUMN conversation_duration_seconds integer,
ADD COLUMN total_customer_words integer,
ADD COLUMN agent_talk_time_percentage float,
ADD COLUMN buying_signals jsonb;

*/
